---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:

  - name: ubuntu
    image: ubuntu:latest
    privileged: true

  - name: centos
    image: quay.io/centos/centos:stream9
    privileged: true

  - name: debian
    image: debian:latest
    privileged: true

provisioner:
  name: ansible
verifier:
  name: ansible
